title: THe Funky Entrepreneur
author: Aanimad
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 I am an budding entrepeneur who write about products which offer best value for the price.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
