title: The chilled Entrepreneur
author: aanimad
email: info@anand.madhu.in
description: > # this means to ignore newlines until "baseurl:"
 An young adventurous Entrepreneur who thinks travelling and passive income is cool
# social links
twitter_username: aanimadh
github_username:  aanimad

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
